### ISSUE TITLE
Polishing failure

### ISSUE THREAD

**Issue by rwhetten** [bcgsc/goldrush-edit#11]
I installed Goldrush using bioconda about two weeks ago, with the goal of using it to assemble a conifer genome from error-corrected ONT data. It reached the polishing phase successfully but then died with an error that appears similar to issue #4 - after it completed the k = 20 bloom filter step, it fails with the error message
```
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
make[1]: *** [/dev/shm/CX4bjGGoQwiRt_PxGKXQhg-226332/batch.ntedited.prepd.sealer_scaffold.upper.fa] Aborted
```
followed by python traceback messages pointing to lines 143, 96, and 78 in goldrush-edit-polish-batch, and line 528 in python3.9/subprocess.py. The job restarted after the first occurrence of this problem, completed the k =20 step, and then threw a different error:
```
[ERROR] ESC[0mProcess pipeline: setpgid failed in parent process.
make[1]: *** [/dev/shm/CX4bjGGoQwiRt_PxGKXQhg-226409/batch.ntedited.prepd.sealer_scaffold.upper.fa] Error 1
```
followed by the same python traceback messages, but now the traceback messages are followed by a make error message:
```
make: *** [$PATH/goldrush_env/bin/goldrush.make:226: w16_x10_golden_path.goldrush-edit-polished.fa] Error 15
```
This error terminated the SLURM job, which automatically restarted and ran until the same point, after the k =20 bloom filter, with a `std::system_error - what(): Resource temporarily unavailable` error very similar to the first one, followed by the make `Error 15` message similar to the second error message, and then the job ended and did not restart.
I have not yet tried to reproduce this problem with a minimal dataset, and I'm not sure how to do that since this is a new assembly with no way to select goldtigs that should overlap and be linked by the polishing step.

**Comment by lcoombe** [comment]
Hi @rwhetten,

The errors you're seeing also look similar to ones reported in this issue: https://github.com/bcgsc/goldrush/issues/95 (specifically the `terminate called after throwing an instance of 'std::system_error'`). For them (and we were able to reproduce on one of our smaller machines), the solution was to run: `ulimit -u 256000` right before launching GoldRush, which increased the `max user processes`. Could you give that a try to see if it works for you? You can also run `ulimit -a` to see the current settings on your machine.

Also, just confirming - you are running GoldRush v1.0.2, and the test demo ran fine for you?

Thank you for your interest in GoldRush!
Lauren

**Comment by vlad0x00** [comment]
@lcoombe Perhaps it makes sense to add that command to the Makefile, like ABySS does. Seems like it's a common problem.

**Comment by lcoombe** [comment]
Yes, agreed Vlad - I'll make an issue for that upstream in GoldRush so we remember to include that in the next release!

**Comment by rwhetten** [comment]
@lcoombe and @vlad0x00 - Thanks for the quick reply! Yes, this is version 1.0.2. I did not run the test demo because I installed from conda, and could not find the tests directory or the goldrush-test-demo.sh script in the conda installation. I found the bcgsc/goldrush#95 issue on Saturday after I posted my comment here, and restarted the job using `ulimit -n 256000`. So far it seems to be working; it has completed the polishing step and moved on to Tigmint; it may take a few days more to see if it will complete the entire pipeline.

**Comment by lcoombe** [comment]
@rwhetten - Great I'm glad that it's working so far! I'll close this for now, but do feel free to open another issue if you encounter any more errors. We'll incorporate that fix into the next release to hopefully avoid that error in the future.

For the test - yes, we don't package that with the conda recipe, so to run it you just need to clone the GoldRush main repository (It's driven by a shell script which will use the GoldRush installation found on your PATH).
